### PR TITLE
Update readiness and liveness probes

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Update to use aries 0.5.3 health check endpoints.

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
The changes in this PR require agents to be running aca-py 0.5.3.
Changes were tested by deploying bcgovimages/aries-cloudagent:0.5.3-beta into the OrgBook-BC dev environment.

**Comment by brianorwhatever** [comment]
@WadeBarnes can you point me towards where I would update my aca-py agent version?

**Comment by WadeBarnes** [comment]
aca-py 0.5.3 has not been released yet, that is why the PR is in draft.

**Comment by esune** [comment]
@brianorwhatever a new image has been pushed to Docker Hub: ` bcgovimages/aries-cloudagent:py36-1.15-0_0.5.3`

**Comment by WadeBarnes** [comment]
@brianorwhatever, Looks like your agent is building off https://github.com/brianorwhatever/aries-vcr.git; https://github.com/brianorwhatever/aries-vcr.git

It should be building off, https://github.com/bcgov/aries-vcr, which have now been updated with the `bcgovimages/aries-cloudagent:py36-1.15-0_0.5.3` image.  Make sue that gets built and deployed before you apply these DC changes.

**Comment by ianco** [comment]
We are now on `bcgovimages/aries-cloudagent:py36-1.15-0_0.5.4-beta2`

**Pull request merged**
