### PR TITLE
Update application.component.html

### PR DESCRIPTION
**Pull request by burock7**
Wording updates and adding conditional labels for specific RLRS Applications

### CODE REVIEW

**Review by burock7 — COMMENTED** [review]
Hi @NovaVic , can you Approve those updates?

**Review by skiselev1 — APPROVED** [review]

**Review by skiselev1 — APPROVED** [review]
I approve this RP

**Review by skiselev1 — APPROVED** [review]

**Review by skiselev1 — APPROVED** [review]

**Review by ashiraziag — APPROVED** [review]
I reviewed the code with Burak and approve

**Comment by burock7** [comment]
Have approved changes but still says "Review required"

**Review by skiselev1 — APPROVED** [review]

**Pull request merged**
